- name: Ensure fetch directory exists
  file:
    path: "{{ fetch_dir }}"
    state: directory
    mode: '0755'

- name: Fetch proxy access logs
  fetch:
    src: /usr/local/kong/logs/access.log
    dest: "{{ fetch_dir }}/"
    flat: yes
  become: yes
  when: kong_action == 'access_logs'

- name: Fetch proxy error logs
  fetch:
    src: /usr/local/kong/logs/error.log
    dest: "{{ fetch_dir }}/"
    flat: yes
  become: yes
  when: kong_action == 'error_logs'

- name: Fetch admin access logs
  fetch:
    src: /usr/local/kong/logs/admin_access.log
    dest: "{{ fetch_dir }}/"
    flat: yes
  become: yes
  when: kong_action == 'admin_access_logs'
