# ---------------------------------
# Kong Service Operations (FINAL)
# ---------------------------------

- name: Start Kong
  shell: sudo -i /usr/local/bin/kong start
  when: kong_action == 'kong_start'
  tags: kong_start

- name: Stop Kong
  shell: sudo -i /usr/local/bin/kong stop
  when: kong_action == 'kong_stop'
  tags: kong_stop

- name: Restart Kong
  shell: sudo -i /usr/local/bin/kong restart
  when: kong_action == 'kong_restart'
  tags: kong_restart
